### ISSUE TITLE
White bottom bar

### ISSUE THREAD

**Issue by Macleykun** [Muirey03/Amandus#1]
iPhone XR
https://macley.stackstorage.com/s/

Btw side note, noctis12, patches then Payment UI needs to be disabled! Not sure if that needs a note like Colorflow does with the Dark media option.

Also, Translucent doesn’t seem to do anything for me. Even without any other tweaks enabled.

**Comment by Muirey03** [comment]
Fixed in v.1.0.1

**Comment by Macleykun** [comment]
Thanks for fixing all those bugs! Can’t wait to see the update coming in!

**Comment by Macleykun** [comment]
![1F1DB833-3F3F-498C-AA05-BF31FACE163B](https://user-images.githubusercontent.com/26381427/72678976-f8b9d100-3aaa-11ea-9a55-83972aff1e78.png)
Updated, also re-installed tweak... is there anything else I can do to help you out?

**Comment by Macleykun** [comment]
So funny update,

I've updated to iOS 13.3 with Unc0ver. And i'm rocking your awsome tweak.

But the white bottom bar doesn't appear anywhere! Tried all the modes on and off, on home and lock screen. But it's completely gone!

I'm still on an A12 device. If you want, you can close this. Thanks for the great work! Can't wait to see what other tweaks you have :D
