### ISSUE TITLE
Unable to swipe to other passes in Wallet

### ISSUE THREAD

**Issue by razer86** [Muirey03/Amandus#2]
In the default UI, I am able to swipe to other passes (non payment cards) after activating the Apple Pay screen. With Amandus installed, I can't swipe to any non payment cards/passes.

An example is the Woolworths Rewards pass.

**Comment by Muirey03** [comment]
Fixed in v.1.0.1

**Comment by razer86** [comment]
Sorry its been such a long time, but thanks for the fix here.
There is a related issue to it now, after swiping to the pass, it does not prompt for FaceID to use the pass.
If I swipe back to any of the payment cards, they each show the FaceID prompt.

If it makes any difference, the pass I am trying to use is Woolworths Rewards (https://www.woolworthsrewards.com.au/digital-wallet-login.html)
